"""Initial migration

Revision ID: 03e64b801903
Revises: 
Create Date: 2025-01-03 20:45:40.252662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e64b801903'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('plex_libraries', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_keys_id'), 'access_keys', ['id'], unique=False)
    op.create_index(op.f('ix_access_keys_key'), 'access_keys', ['key'], unique=True)
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_id'), 'admin_user', ['id'], unique=False)
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key_id', sa.Integer(), nullable=True),
    sa.Column('invited_email', sa.String(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_table('plex_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plex_id', sa.String(), nullable=True),
    sa.Column('plex_username', sa.String(), nullable=True),
    sa.Column('access_key_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plex_id')
    )
    op.create_index(op.f('ix_plex_users_id'), 'plex_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plex_users_id'), table_name='plex_users')
    op.drop_table('plex_users')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin_user')
    op.drop_table('admin_user')
    op.drop_index(op.f('ix_access_keys_key'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_id'), table_name='access_keys')
    op.drop_table('access_keys')
    # ### end Alembic commands ###
