"""Add SetupState model

Revision ID: d093ba44db3a
Revises: 03e64b801903
Create Date: 2025-01-03 21:21:10.073332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd093ba44db3a'
down_revision: Union[str, None] = '03e64b801903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_created', sa.Boolean(), nullable=True),
    sa.Column('plex_configured', sa.Boolean(), nullable=True),
    sa.Column('smtp_configured', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_state_id'), 'setup_state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setup_state_id'), table_name='setup_state')
    op.drop_table('setup_state')
    # ### end Alembic commands ###
